### ISSUE TITLE
all collection element use collections last elements value as its value

### ISSUE THREAD

**Issue by lordjancso** [kristijanhusak/laravel4-form-builder#6]
I have my User model mapped to a form.
Users can have multiple addresses (Address model).
There is one to many relationship between them.
For example if my user have 3 addresses, form will display the 3rd element 3 times.

**Comment by kristijanhusak** [comment]
Did you set up `property` option for collection? (https://github.com/kristijanhusak/laravel4-form-builder#collection).
If that's not working, please give me the dump of model that you pass to form, in array format. Something like this:

```
User::with('addresses')->find($id)->toArray();
```

**Comment by lordjancso** [comment]
I didn't set up property option because as far as I know id is the default and I'm ok with that.
I can't dump my model right now for you, but User is an User object and it have addresses property which is a Collection. I can iterate it, dump or whatever I want. So its a by the book one-to-many relationship. Nothing fancy.
Should I pass it as array? Because in controller I pass it as a model object... I will check this out tomorrow but I guess this doesn't really matter.

**Comment by kristijanhusak** [comment]
I've got same issue opened on version for Laravel 5. Will check it out tomorrow and let you know.

**Comment by kristijanhusak** [comment]
@lordjancso 
I fixed it, should be working properly now. Do a composer update and test it, if it's fine, please close the issue. Thanks.

**Comment by lordjancso** [comment]
@kristijanhusak 
Thank you for your fast reaction. Its working now with collections on level 1.
So User is level 0, Address is level 1, but if I add a level 2 collection (for example Car - how many cars do you have on this address), which is a form collection too, its still not working.
What do you think, can your FormBuilder handle multiple level nestings?

**Comment by kristijanhusak** [comment]
@lordjancso 
I think it should work. Will test it out and let you know.

**Comment by lordjancso** [comment]
@kristijanhusak 
Thank you very much!

**Comment by lordjancso** [comment]
I guess, the problem should be here, because $model is null in level 2 collections.
https://github.com/kristijanhusak/laravel4-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/ChildFormType.php#L91

**Comment by kristijanhusak** [comment]
I tested it, and it worked for me with this data structure:

``` php
        $userModel = [
            'name' => 'John Doe',
            'addresses' => [
                [
                    'name' => 'add1',
                    'cars' => [
                        ['brand' => 'brand1'],
                        ['brand' => 'brand2'],
                        ['brand' => 'brand3']
                    ]
                ]
                [
                    'name' => 'add2',
                    'cars' => [
                        ['brand' => 'brand4'],
                        ['brand' => 'brand5'],
                        ['brand' => 'brand6']
                    ]
                ]
            ]
        ];

```

Are you sure you are passing proper data?

**Comment by lordjancso** [comment]
Hmm.. Yeah, its working for me now, if I convert the given model to array. So in controller:

```
        $form = FormBuilder::create('UserForm', array(
            'model' => User::find($id)->toArray() //this toArray is necessary
        ));
```

Maybe you should check if model is object, then convert it to array. Just for sure.
Thank you for your help. I close this!

**Comment by kristijanhusak** [comment]
I am checking if the model is object or array, and get data according to that (this [line](https://github.com/kristijanhusak/laravel4-form-builder/blob/master/src/Kris/LaravelFormBuilder/Fields/FormField.php#L124)).

Relationship data must be pulled using `with` method, otherwise data will not be visible in the form.
So for example `User::with('addresses', 'adresses.cars')->find($id)`. If not pulled, both array or object type is not working, so that is not an issue for you if it works as array. I'm really confused.

I tested it on 1 level deep collection. But it should work properly deeper.

**Comment by lordjancso** [comment]
I'm using 'with' property, but not inline as you do.
There is a protected array in User model and I declare these relationships there.

```
class User extends Eloquent
{
    protected $table = 'users';
    protected $with = array('addresses');
    // ...
```

Try your example with data from database (model) without converting it to array. It won't work then, just if you call ->toArray() on it.

**Comment by kristijanhusak** [comment]
I tried without `toArray`, and it worked out. But i didn't test 2 level deep, only 1 level. Maybe there's some issue with deeper data. Couldn't track it myself, if you find a problem let me know.

**Comment by lordjancso** [comment]
Yeah, I had the same problem. Converting model to array solves the problem!
